version: "3"

services:
  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit
    ports:
      - "24224:24224"
    volumes:
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
    
  my_collector:
    volumes:
      - ./otel-col-config.yaml:/etc/otel/config.yaml
    ports:
      - 55681:55681
    image: otel/opentelemetry-collector-contrib
