receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006
exporters:
  kafka/logs:
    protocol_version: 2.0.0
    encoding: otlp_json
    brokers:
      - "kafka:9092"
    topic: logs
  logging:
    loglevel: debug
service:
  pipelines:
    logs:
      receivers: [ fluentforward ]
      exporters: [ logging,kafka/logs ]